import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTable1775237057390 implements MigrationInterface {
    name = 'CreateTable1775237057390'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'user', 'staff')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "full_name" character varying(160) NOT NULL, "phone" character varying(30), "avatar_url" character varying(255), "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "actors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "image_url" character varying(255), CONSTRAINT "PK_d8608598c2c4f907a78de2ae461" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movie_casts" ("movie_id" uuid NOT NULL, "actor_id" uuid NOT NULL, "role_name" character varying(100), "display_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_b4a419d86c665b3cf1f2cb1dacb" PRIMARY KEY ("movie_id", "actor_id"))`);
        await queryRunner.query(`CREATE TABLE "genres" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, CONSTRAINT "PK_80ecd718f0f00dde5d77a9be842" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f105f8230a83b86a346427de94" ON "genres" ("name") `);
        await queryRunner.query(`CREATE TABLE "movie_genres" ("movie_id" uuid NOT NULL, "genre_id" uuid NOT NULL, CONSTRAINT "PK_ec45eae1bc95d1461ad55713ffc" PRIMARY KEY ("movie_id", "genre_id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "movie_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."movies_age_rating_enum" AS ENUM('p', 'k', 't13', 't16', 't18')`);
        await queryRunner.query(`CREATE TYPE "public"."movies_status_enum" AS ENUM('coming_soon', 'now_showing', 'ended', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "movies" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "slug" character varying(200) NOT NULL, "description" text, "duration_minutes" integer NOT NULL, "poster_url" character varying(255), "banner_url" character varying(255), "trailer_url" character varying(255), "director" character varying(160), "release_date" date, "age_rating" "public"."movies_age_rating_enum", "critic_score" numeric(3,1), "audience_score" numeric(3,1), "status" "public"."movies_status_enum" NOT NULL DEFAULT 'coming_soon', CONSTRAINT "PK_c5b2c134e871bfd1c2fe7cc3705" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ed86498aefe0e545548ca31b7" ON "movies" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."seats_type_enum" AS ENUM('standard', 'vip', 'couple', 'wheelchair')`);
        await queryRunner.query(`CREATE TABLE "seats" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "seat_row" character varying(5) NOT NULL, "seat_number" integer NOT NULL, "type" "public"."seats_type_enum" NOT NULL DEFAULT 'standard', "base_price" numeric(10,2) NOT NULL DEFAULT '0', "price_adjustment" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_b5ae84e0d59952a8e14016fbd96" UNIQUE ("room_id", "seat_row", "seat_number"), CONSTRAINT "PK_3fbc74bb4638600c506dcb777a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "booking_seats" ("booking_id" uuid NOT NULL, "showtime_seat_id" uuid NOT NULL, "seat_id" uuid NOT NULL, "unit_price" numeric(10,2) NOT NULL, CONSTRAINT "UQ_af6e1b202afcfa8a29a639704c0" UNIQUE ("booking_id", "seat_id"), CONSTRAINT "PK_f764e850de3ab3648fbf55a13b9" PRIMARY KEY ("booking_id", "showtime_seat_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."showtime_seats_status_enum" AS ENUM('available', 'locked', 'reserved', 'sold', 'unavailable')`);
        await queryRunner.query(`CREATE TABLE "showtime_seats" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "showtime_id" uuid NOT NULL, "seat_id" uuid NOT NULL, "price" numeric(10,2) NOT NULL, "status" "public"."showtime_seats_status_enum" NOT NULL DEFAULT 'available', "locked_by_user_id" uuid, "lock_expires_at" TIMESTAMP, CONSTRAINT "UQ_67fd77b244071aed7faad558a80" UNIQUE ("showtime_id", "seat_id"), CONSTRAINT "PK_4d527cc642f73f71ef28d0aadef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."showtimes_format_enum" AS ENUM('2d', '3d', 'imax', '4dx', 'vip')`);
        await queryRunner.query(`CREATE TYPE "public"."showtimes_status_enum" AS ENUM('draft', 'on_sale', 'sold_out', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "showtimes" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "movie_id" uuid NOT NULL, "cinema_id" uuid NOT NULL, "room_id" uuid NOT NULL, "show_date" date NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "format" "public"."showtimes_format_enum" NOT NULL DEFAULT '2d', "base_price" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."showtimes_status_enum" NOT NULL DEFAULT 'draft', CONSTRAINT "PK_2d979092e692ec1a7b505893ee2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_format_enum" AS ENUM('2d', '3d', 'imax', '4dx', 'vip')`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_status_enum" AS ENUM('active', 'inactive', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "rooms" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cinema_id" uuid NOT NULL, "name" character varying(50) NOT NULL, "format" "public"."rooms_format_enum" NOT NULL DEFAULT '2d', "total_rows" integer NOT NULL, "total_columns" integer NOT NULL, "total_seats" integer NOT NULL, "status" "public"."rooms_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "UQ_4ea38a75ad541b3981826187783" UNIQUE ("cinema_id", "name"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('booking_confirmed', 'booking_rejected', 'showtime_reminder', 'promotion', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "booking_id" uuid, "is_read" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('cash', 'vnpay', 'momo', 'zalopay', 'stripe', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'paid', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "payments" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "provider" "public"."payments_provider_enum" NOT NULL, "payment_method" character varying(50), "transaction_id" character varying(100), "amount" numeric(10,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "paid_at" TIMESTAMP, CONSTRAINT "REL_e86edf76dc2424f123b9023a2b" UNIQUE ("booking_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e86edf76dc2424f123b9023a2b" ON "payments" ("booking_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3c324ca49dabde7ffc0ef64675" ON "payments" ("transaction_id") `);
        await queryRunner.query(`CREATE TYPE "public"."products_category_enum" AS ENUM('combo', 'food', 'drink', 'merchandise')`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('active', 'inactive', 'out_of_stock')`);
        await queryRunner.query(`CREATE TABLE "products" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "category" "public"."products_category_enum" NOT NULL, "price" numeric(10,2) NOT NULL, "stock" integer NOT NULL DEFAULT '0', "status" "public"."products_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "booking_products" ("booking_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price" numeric(10,2) NOT NULL, CONSTRAINT "PK_50543e0ac890a88ad85899f6299" PRIMARY KEY ("booking_id", "product_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_logs_from_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'checked_in', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_logs_to_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'checked_in', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "booking_status_logs" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "from_status" "public"."booking_status_logs_from_status_enum", "to_status" "public"."booking_status_logs_to_status_enum" NOT NULL, "acted_by_user_id" uuid, "reason" text, CONSTRAINT "PK_f5ec1a5a9046c21b40ad1c35561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'checked_in', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_code" character varying(30) NOT NULL, "user_id" uuid, "showtime_id" uuid NOT NULL, "room_id" uuid NOT NULL, "cinema_id" uuid NOT NULL, "movie_id" uuid NOT NULL, "customer_name" character varying(160) NOT NULL, "customer_email" character varying(255) NOT NULL, "customer_phone" character varying(30), "payment_method" character varying(50), "qr_code_url" character varying(255), "total_price" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending', "approved_by" uuid, "approved_at" TIMESTAMP, "rejected_by" uuid, "rejected_at" TIMESTAMP, "rejection_reason" text, "checked_in_by" uuid, "checked_in_at" TIMESTAMP, "notes" text, "expires_at" TIMESTAMP, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_796e0227e4beff186bdd72ac53" ON "bookings" ("booking_code") `);
        await queryRunner.query(`CREATE TABLE "cinema_features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, CONSTRAINT "PK_42c67aef2b9849f4a82549d9d29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_81d755e0566c8ef3c003ba8647" ON "cinema_features" ("name") `);
        await queryRunner.query(`CREATE TABLE "cinema_feature_maps" ("cinema_id" uuid NOT NULL, "feature_id" uuid NOT NULL, CONSTRAINT "PK_775257e8c4f85ab95101d0a1e17" PRIMARY KEY ("cinema_id", "feature_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cinemas_status_enum" AS ENUM('active', 'inactive', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "cinemas" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "address" text, "province" character varying(100), "hotline" character varying(30), "image_url" character varying(255), "lat" numeric(10,7), "lng" numeric(10,7), "status" "public"."cinemas_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_5c49a5f87710ce93fad49d72320" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_profiles" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "employee_code" character varying(50) NOT NULL, "job_title" character varying(100), "cinema_id" uuid, "shift_name" character varying(100), "shift_start" TIME, "shift_end" TIME, CONSTRAINT "PK_223deb3f390b28562fad70eefed" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_313fde1324563a4016e3e154eb" ON "staff_profiles" ("employee_code") `);
        await queryRunner.query(`CREATE TYPE "public"."customer_profiles_membership_level_enum" AS ENUM('standard', 'silver', 'gold', 'platinum')`);
        await queryRunner.query(`CREATE TABLE "customer_profiles" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "membership_level" "public"."customer_profiles_membership_level_enum" NOT NULL DEFAULT 'standard', "points" integer NOT NULL DEFAULT '0', "total_spent" numeric(12,2) NOT NULL DEFAULT '0', "birth_date" date, "gender" character varying(20), CONSTRAINT "PK_99617dd6d452ad43dd992a79933" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`ALTER TABLE "movie_casts" ADD CONSTRAINT "FK_14a5c48b111eff2a59b20b2b332" FOREIGN KEY ("movie_id") REFERENCES "movies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movie_casts" ADD CONSTRAINT "FK_db755699781e08c0059d95e207d" FOREIGN KEY ("actor_id") REFERENCES "actors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movie_genres" ADD CONSTRAINT "FK_ae967ce58ef99e9ff3933ccea48" FOREIGN KEY ("movie_id") REFERENCES "movies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movie_genres" ADD CONSTRAINT "FK_bbbc12542564f7ff56e36f5bbf6" FOREIGN KEY ("genre_id") REFERENCES "genres"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_563501cf3faa75a1ca40be84f82" FOREIGN KEY ("movie_id") REFERENCES "movies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seats" ADD CONSTRAINT "FK_657a29871b8dd6a5107da320458" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_seats" ADD CONSTRAINT "FK_25c8b5c1e010af1cd2f699c5926" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_seats" ADD CONSTRAINT "FK_ce3eaf629a9df599803acd0d936" FOREIGN KEY ("seat_id") REFERENCES "seats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_seats" ADD CONSTRAINT "FK_5264ace5a1c964a6f9da279af8c" FOREIGN KEY ("showtime_seat_id") REFERENCES "showtime_seats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showtime_seats" ADD CONSTRAINT "FK_45e3e0a137fdd29ea07ec76c045" FOREIGN KEY ("showtime_id") REFERENCES "showtimes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showtime_seats" ADD CONSTRAINT "FK_947e54d5a7ffab520095d10410a" FOREIGN KEY ("seat_id") REFERENCES "seats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showtime_seats" ADD CONSTRAINT "FK_9bbb8f63f3f8295b4cdda67e10c" FOREIGN KEY ("locked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showtimes" ADD CONSTRAINT "FK_cbe689b0c116fbc866d8ea21759" FOREIGN KEY ("movie_id") REFERENCES "movies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showtimes" ADD CONSTRAINT "FK_d8434cba552cd29c2496d4067bf" FOREIGN KEY ("cinema_id") REFERENCES "cinemas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showtimes" ADD CONSTRAINT "FK_7dac5a1df6dbc1f355112a11d8d" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_b7e045af2f3b84e1f2cef0e3dd5" FOREIGN KEY ("cinema_id") REFERENCES "cinemas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_3f5c2196c2b2af99a4697e51741" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_products" ADD CONSTRAINT "FK_6d2ed280dbae56f72547110bceb" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_products" ADD CONSTRAINT "FK_9c6915fb253c8bd604320e3569a" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_status_logs" ADD CONSTRAINT "FK_21c42d93bdff461b6abfaf19a72" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_status_logs" ADD CONSTRAINT "FK_108e6d83f573a0b2ea68aa69800" FOREIGN KEY ("acted_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64cd97487c5c42806458ab5520c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_311925ef3f94966ea9482de9df3" FOREIGN KEY ("showtime_id") REFERENCES "showtimes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_0b0fc32fe6bd0119e281628df7a" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_380ce05fce8f8146637718d836c" FOREIGN KEY ("cinema_id") REFERENCES "cinemas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_de236ee7801bf0a1f7be289b2f2" FOREIGN KEY ("movie_id") REFERENCES "movies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_f029d2aa232d51e6c6742cd8e2d" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_4beda8dd4a15a24d162af251b66" FOREIGN KEY ("rejected_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_d8438267356056afa59f5c2dfd9" FOREIGN KEY ("checked_in_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cinema_feature_maps" ADD CONSTRAINT "FK_c0796b369f565bc8e79e0efb185" FOREIGN KEY ("cinema_id") REFERENCES "cinemas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cinema_feature_maps" ADD CONSTRAINT "FK_607391ef194b83217d608f702e2" FOREIGN KEY ("feature_id") REFERENCES "cinema_features"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_223deb3f390b28562fad70eefed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_4a48542b607d5133eca2fb1b7e9" FOREIGN KEY ("cinema_id") REFERENCES "cinemas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ADD CONSTRAINT "FK_99617dd6d452ad43dd992a79933" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customer_profiles" DROP CONSTRAINT "FK_99617dd6d452ad43dd992a79933"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_4a48542b607d5133eca2fb1b7e9"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_223deb3f390b28562fad70eefed"`);
        await queryRunner.query(`ALTER TABLE "cinema_feature_maps" DROP CONSTRAINT "FK_607391ef194b83217d608f702e2"`);
        await queryRunner.query(`ALTER TABLE "cinema_feature_maps" DROP CONSTRAINT "FK_c0796b369f565bc8e79e0efb185"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_d8438267356056afa59f5c2dfd9"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_4beda8dd4a15a24d162af251b66"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_f029d2aa232d51e6c6742cd8e2d"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_de236ee7801bf0a1f7be289b2f2"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_380ce05fce8f8146637718d836c"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_0b0fc32fe6bd0119e281628df7a"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_311925ef3f94966ea9482de9df3"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64cd97487c5c42806458ab5520c"`);
        await queryRunner.query(`ALTER TABLE "booking_status_logs" DROP CONSTRAINT "FK_108e6d83f573a0b2ea68aa69800"`);
        await queryRunner.query(`ALTER TABLE "booking_status_logs" DROP CONSTRAINT "FK_21c42d93bdff461b6abfaf19a72"`);
        await queryRunner.query(`ALTER TABLE "booking_products" DROP CONSTRAINT "FK_9c6915fb253c8bd604320e3569a"`);
        await queryRunner.query(`ALTER TABLE "booking_products" DROP CONSTRAINT "FK_6d2ed280dbae56f72547110bceb"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_3f5c2196c2b2af99a4697e51741"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_b7e045af2f3b84e1f2cef0e3dd5"`);
        await queryRunner.query(`ALTER TABLE "showtimes" DROP CONSTRAINT "FK_7dac5a1df6dbc1f355112a11d8d"`);
        await queryRunner.query(`ALTER TABLE "showtimes" DROP CONSTRAINT "FK_d8434cba552cd29c2496d4067bf"`);
        await queryRunner.query(`ALTER TABLE "showtimes" DROP CONSTRAINT "FK_cbe689b0c116fbc866d8ea21759"`);
        await queryRunner.query(`ALTER TABLE "showtime_seats" DROP CONSTRAINT "FK_9bbb8f63f3f8295b4cdda67e10c"`);
        await queryRunner.query(`ALTER TABLE "showtime_seats" DROP CONSTRAINT "FK_947e54d5a7ffab520095d10410a"`);
        await queryRunner.query(`ALTER TABLE "showtime_seats" DROP CONSTRAINT "FK_45e3e0a137fdd29ea07ec76c045"`);
        await queryRunner.query(`ALTER TABLE "booking_seats" DROP CONSTRAINT "FK_5264ace5a1c964a6f9da279af8c"`);
        await queryRunner.query(`ALTER TABLE "booking_seats" DROP CONSTRAINT "FK_ce3eaf629a9df599803acd0d936"`);
        await queryRunner.query(`ALTER TABLE "booking_seats" DROP CONSTRAINT "FK_25c8b5c1e010af1cd2f699c5926"`);
        await queryRunner.query(`ALTER TABLE "seats" DROP CONSTRAINT "FK_657a29871b8dd6a5107da320458"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_563501cf3faa75a1ca40be84f82"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "movie_genres" DROP CONSTRAINT "FK_bbbc12542564f7ff56e36f5bbf6"`);
        await queryRunner.query(`ALTER TABLE "movie_genres" DROP CONSTRAINT "FK_ae967ce58ef99e9ff3933ccea48"`);
        await queryRunner.query(`ALTER TABLE "movie_casts" DROP CONSTRAINT "FK_db755699781e08c0059d95e207d"`);
        await queryRunner.query(`ALTER TABLE "movie_casts" DROP CONSTRAINT "FK_14a5c48b111eff2a59b20b2b332"`);
        await queryRunner.query(`DROP TABLE "customer_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."customer_profiles_membership_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_313fde1324563a4016e3e154eb"`);
        await queryRunner.query(`DROP TABLE "staff_profiles"`);
        await queryRunner.query(`DROP TABLE "cinemas"`);
        await queryRunner.query(`DROP TYPE "public"."cinemas_status_enum"`);
        await queryRunner.query(`DROP TABLE "cinema_feature_maps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81d755e0566c8ef3c003ba8647"`);
        await queryRunner.query(`DROP TABLE "cinema_features"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_796e0227e4beff186bdd72ac53"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP TABLE "booking_status_logs"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_logs_to_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_logs_from_status_enum"`);
        await queryRunner.query(`DROP TABLE "booking_products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c324ca49dabde7ffc0ef64675"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e86edf76dc2424f123b9023a2b"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_format_enum"`);
        await queryRunner.query(`DROP TABLE "showtimes"`);
        await queryRunner.query(`DROP TYPE "public"."showtimes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."showtimes_format_enum"`);
        await queryRunner.query(`DROP TABLE "showtime_seats"`);
        await queryRunner.query(`DROP TYPE "public"."showtime_seats_status_enum"`);
        await queryRunner.query(`DROP TABLE "booking_seats"`);
        await queryRunner.query(`DROP TABLE "seats"`);
        await queryRunner.query(`DROP TYPE "public"."seats_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ed86498aefe0e545548ca31b7"`);
        await queryRunner.query(`DROP TABLE "movies"`);
        await queryRunner.query(`DROP TYPE "public"."movies_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."movies_age_rating_enum"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "movie_genres"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f105f8230a83b86a346427de94"`);
        await queryRunner.query(`DROP TABLE "genres"`);
        await queryRunner.query(`DROP TABLE "movie_casts"`);
        await queryRunner.query(`DROP TABLE "actors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
